config/routes.rb
Rails.application.routes.draw do
  root :to => "application#index"
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  resources :users do
    resources :images, only: [:index]
  end
  resources :images, except: [:index] do
    resources :tags
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :user
  has_many :tags, dependent: :destroy
  has_many :tagged_users, through: :tags, source: :user
  has_attached_file :img_file, styles: { default: "600x600", thumb: "100x100"}, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :img_file, content_type: /\Aimage\/.*\z/
  validates :img_file_file_name, :presence => true
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :user
  belongs_to :image

  validates :user_id, :uniqueness => {:scope => :image_id}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tags
  has_many :images
  has_many :favorite_images, dependent: :destroy, source: :image
  has_many :tagged_images, through: :tags, dependent: :destroy, source: :image
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :username
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_filter :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit :username, :email, :password, :password_confirmation
    end
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @user = User.find(params[:user_id])
    @images = Image.all
  end

  def show
    @image = Image.find(params[:id])
  end

  def new
    @user = current_user
    @image = @user.images.new
    if @user.id != current_user.id
      redirect_to user_path(@user)
    end
  end

  def create
    @user = current_user
    @image = @user.images.new(image_params)
      if @image.save
        flash[:success] = "Image uploaded!"
        redirect_to user_path(@user)
      else
        flash[:alert] = "Upload unsuccessful, please try again!"
        render :new
    end
  end

  def destroy
    @image = Image.find(params[:id])
    if @image.user_id === current_user.id
      @image.destroy
      flash[:error] = "Image deleted!"
    end
    redirect_to user_path(@image.user)
  end

private
  def image_params
    params.require(:image).permit(:img_file)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  def show
    @image = Image.find(params[:image_id])
    @tag = Tag.find(params[:id])
  end

  def new
    @image = Image.find(params[:image_id])
    @tag = @image.tags.new
  end

  def create
    @image = Image.find(params[:image_id])
    @tag = @image.tags.new(tag_params)
    @user = User.find_by_id(@tag.user_id)
      if @tag.save
        flash[:success] = "Tag recorded!"
        redirect_to image_path(@image)
      else
        flash[:alert] = "Tag unsuccessful, please try again!"
        render :_new
    end
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    redirect_to image_path(@tag.image)
  end

private
  def tag_params
    params.require(:tag).permit(:user_id, :image_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
   case level
     when 'notice' then "alert alert-info"
     when 'success' then "alert alert-success"
     when 'error' then "alert alert-danger"
     when 'alert' then "alert alert-warning"
   end
 end
end

app/views/application/index.html.erb
<div class="homepage">
  <h1>The home for all your photos.</h1>
  <h5>Upload, access, organize, edit, and share your photos from any device, from anywhere in the world.</h5>
</div>

app/views/images/index.html.erb
<% @user.images.each do |image| %>
  <%= image.img_file %>
<% end %>

app/views/images/new.html.erb
<%= form_for [@user, @image], url: images_path(@image) do |form| %>
  <%= form.file_field :img_file %>
  <%= form.submit %>
<% end %>

app/views/images/show.html.erb
<%= image_tag @image.img_file.url %>

<%= render "tags/new" %>

<% if @image.tags.any? %>
  <% @image.tags.each do |tag| %>
    <%= button_to tag.user.username, image_tag_path(tag.image, tag), class:"btn btn-success", :method =>"delete" %>
  <% end %>
<% end %>


<% if @image.user_id === current_user.id %>
  <p><%= button_to "delete image", image_path(@image), :method => "delete" %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlickrClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar" role="navigation">
      <div class ='container'>
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to root_path do %>
            <%= image_tag 'logo.png', class: 'navbar-brand' %>
          <% end %>
          <ul class="nav navbar-nav">
            <% if user_signed_in?%>
            <li><%= link_to "View Profile", user_path(current_user.id)%></li>
            <li><a href="#">Create</a></li>
            <% end %>
          </ul>
        </div>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            <li class="bumpdown">Logged in as <%= current_user.email %></li>
          <% else %>
            <li><%= link_to "Sign In", new_user_session_path %></li>
            <li><%= button_to "Sign Up", new_user_registration_path, :method => "get", class: 'btn btn-primary' %></button></li>
          <% end %>
        </ul>
      </div>
    </nav>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="<%= flash_class(key) %>">
          <%= value %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/tags/_new.html.erb
<%= form_for [@image, Tag.new] do |f| %>
  <%= f.label :tags %>
  <%= f.collection_select :user_id, User.all, :id, :username, include_blank: true %>
  <%= f.submit  %>
<% end %>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <%= link_to user.username, user_path(user) %>
<% end %>

app/views/users/show.html.erb
<div class="jumbotron">
  <h1><%= @user.username %></h1>
  <% if @user.id === current_user.id %>
    <%= button_to "New Image", new_image_path, class: 'btn-primary btn', :method => "get" %>
  <% end %>
</div>

<% if @user.images.any? %>
    <% @user.images.each do |image| %>
      <%=link_to image_path(image) do %>
        <%= image_tag image.img_file.url(:default), class:"image-tile" %>
      <% end %>
    <% end %>
<% end %>

<h1>Tagged Images for <%=@user.username%></h1>
<% if @user.tagged_images.any? %>
  <% @user.tagged_images.each do |tagged_image| %>
    <%= link_to image_path(tagged_image) do%>
      <%= image_tag tagged_image.img_file.url(:default), class:"image-tile" %>
    <% end %>
  <% end %>
<% end %>